version: "3.9"
services:
  baitbot:
    build:
      dockerfile: docker/Dockerfile
      context: ../
    env_file:
        - ../.env
    depends_on:
      - baitbot_redis
      - baitbot_memcached
    container_name: baitbot
    restart: unless-stopped

  baitbot_redis:
    image: redis:6-alpine
    ports:
      - '127.0.0.1:35006:6379'
    volumes:
      - redis:/var/lib/redis
    container_name: baitbot_redis
    restart: unless-stopped

  baitbot_memcached:
    image: 'bitnami/memcached:latest'
    ports:
      - '11211:11211'
    environment:
      - MEMCACHED_MAX_ITEM_SIZE=8388608
      - MEMCACHED_MAX_CONNECTIONS=2000
      - MEMCACHED_THREADS=4
    networks:
      - default
    container_name: baitbot_memcached
    restart: unless-stopped

volumes:
  redis:
    driver: local
  tools:
    driver: local

networks:
  default:
    name: baitnet
    