
version: "3.9"
services:
  baitbot:
    build:
      dockerfile: docker/Dockerfile
      context: ../
    command: run
    environment:
      - ENV=local
    env_file:
        - ../.env
    restart: unless-stopped

networks:
  default:
    name: baitnet
    